# Generated by Django 4.2.9 on 2024-02-02 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2024, 2, 9, 16, 47, 10, 484942, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
